name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USER }}
#         password: ${{ secrets.DOCKER_PASSWD }}
    - name: Build
      run: |
       git clone --depth=1 --branch=main https://github.com/armbian/build
       cp -r kernel u-boot build/
       cd build
       ./compile.sh BOARD=orangepi4-lts BRANCH=current BUILD_DESKTOP=no  KERNEL_CONFIGURE=no  BUILD_MINIMAL=yes RELEASE=jammy CLEAN_LEVEL="make,oldcache,images"

